### PR TITLE
Remove LHSDesign

### PR DESCRIPTION
**Pull request by jschueller**
needs openturns/openturns#310
The results change! Any clue ?

### CODE REVIEW

**Comment by sofianehaddad** [comment]
Generation of experiments is totally different (working by blocks in LHSExperiment wheras working cell by cell in LHSDesign)  and this leads to initial designs 
However some space filling measures seem strange...

**Comment by jschueller** [comment]
@sofianehaddad Which results are you referring to ?
I reran some validation tests and got the expected (but different) values (for example validate_SA_small.py and got the c2 <= 0.0664, and mindist > 0.27).

**Comment by sofianehaddad** [comment]
@jschueller 

I was thinking about Monte-Carlo tests. 
For Monte-Carlo we should ensure that for very large N, we converge to SA results proposed in
http://openturns.github.io/otlhs/master/developer_guide/validation/validation.html#validation-of-simulated-annealing-algorithm

**Comment by jschueller** [comment]
Ok, here's the output of validate_MC_small.py: the c2 criteria (2nd column) is decreasing with nsimu (and below the reference 0.06xxx):
```
dimension=2, size=10
INF - Warning! The description of the distribution ComposedDistribution is [X0,X0] and cannot identify uniquely the marginal distribution. Use default description instead.
100 0.065433 0.003310
200 0.065433 0.006674
400 0.065433 0.013116
800 0.065433 0.034383
1600 0.065433 0.092744
3200 0.065433 0.153347
6400 0.063380 0.312833
12800 0.062975 0.623108
25600 0.061042 1.253616
51200 0.061042 2.490888
102400 0.061042 4.947906
204800 0.061042 10.049585
409600 0.061042 19.993349
cpu time=19.185615
dimension=2, size=10,mc=class=MonteCarloLHS name=Unnamed lhs=class=LHSExperiment name=Unnamed distribution=class=ComposedDistribution name=ComposedDistribution dimension=2 copula=class=IndependentCopula name=IndependentCopula dimension=2 marginal[0]=class=Uniform name=Uniform dimension=1 a=0 b=1 marginal[1]=class=Uniform name=Uniform dimension=1 a=0 b=1 size=10 alwaysShuffle=true random shift=true spaceFilling=class=SpaceFilling implementation=class=SpaceFillingMinDist minimization=false simulation size=409600
optimal value=0.3025161085033095 c2=0.06842197493644978 phiP=3.313021118066551 minDist=0.3025161085033095
INF - (previous message repeated 13 times)
INF - *** Log End ***
```

**Comment by sofianehaddad** [comment]
Seems good

**Comment by jschueller** [comment]
@sofianehaddad thanks, I'll merge this on 1.8rc2

**Pull request merged**
